services:
  - type: web
    name: transpobot-frontend
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://transpobot-backend.onrender.com/api
